import waterHeaters from "../../../assets/blog1.jpg";
import faucets from "../../../assets/blog2.jpg";
import toiletRepair from "../../../assets/blog3.jpg";

export const categoryOptions = [
    "All",
    "Bathroom Plumbing",
    "Drain Service",
    "Emergency Plumbing",
    "Heating Service",
    "Kitchen Plumbing",
    "Leak Detection",
    "Pipe Repair",
    "Plumbing Basics",
    "Plumbing System",
    "Save Money",
    "Seasonal Plumbing",
    "Sewer Service",
    "Toilet",
    "Uncategorized",
    "Water Heater",
    "Water Quality"
];

export const sortOptions = [
    { name: "Most Recent", value: "dateDesc" },
    { name: "Oldest", value: "dateAsc" },
    { name: "Most Viewed", value: "viewsDesc" },
    { name: "Title (A-Z)", value: "titleAsc" },
	{ name: "Title (Z-A)", value: "titleDesc" },
];

export const posts = [
    {
        id: 1,
        title: "Water Heater Repair and Replacement",
        image: waterHeaters,
        author: "John Doe",
        date: "October 10, 2025",
        views: 500,
        link: "/blog/water-heater-installation",
        description: "Expert repair and maintenance for tank and tankless water heaters, ensuring reliable hot water for your home year-round.",
        keywords: ["Water Heater"],
    },
    {
        id: 2,
        title: "Kitchen Faucet Installation Guide",
        image: faucets,
        author: "Jane Smith",
        date: "October 3, 2025",
        views: 5000,
        link: "/blog/faucet-replacement",
        description: "Professional faucet installation and replacement services, improving functionality and aesthetics in kitchens and bathrooms.",
        keywords: ["Kitchen Plumbing"],
    },
    {
        id: 3,
        title: "Toilet Repair and Maintenance Tips",
        image: toiletRepair,
        author: "Jim Bob",
        date: "September 27, 2025",
        views: 999999999,
        link: "/blog/toilet-repair",
        description: "Comprehensive toilet repair and maintenance services to prevent leaks, clogs, and ensure long-lasting performance.",
        keywords: ["Toilet"],
    },
    {
        id: 4,
        title: "Emergency Water Heater Services",
        image: waterHeaters,
        author: "John Doe",
        date: "September 20, 2025",
        views: 500,
        link: "/blog/emergency-water-heater",
        description: "24/7 emergency water heater repair services for when you need hot water restored quickly and efficiently.",
        keywords: ["Water Heater", "Emergency Plumbing"],
    },
    {
        id: 5,
        title: "Modern Bathroom Faucet Trends",
        image: faucets,
        author: "Jane Smith",
        date: "September 15, 2025",
        views: 500,
        link: "/blog/bathroom-faucets",
        description: "Discover the latest trends in bathroom faucet design and how to choose the perfect fixtures for your space.",
        keywords: ["Bathroom Plumbing"],
    },
    {
        id: 6,
        title: "Common Toilet Problems and Solutions",
        image: toiletRepair,
        author: "Jim Bob",
        date: "September 8, 2025",
        views: 500,
        link: "/blog/toilet-problems",
        description: "Learn about the most common toilet issues homeowners face and how professional plumbers can solve them effectively.",
        keywords: ["Toilet", "Plumbing Basics"],
    },
    {
        id: 7,
        title: "Tankless Water Heater Benefits",
        image: waterHeaters,
        author: "John Doe",
        date: "August 30, 2025",
        views: 500,
        link: "/blog/tankless-water-heater",
        description: "Explore the energy-saving benefits of tankless water heaters and why they're becoming the preferred choice for homeowners.",
        keywords: ["Water Heater", "Save Money"],
    },
    {
        id: 8,
        title: "How to Fix a Leaky Faucet",
        image: faucets,
        author: "Jane Smith",
        date: "August 22, 2025",
        views: 500,
        link: "/blog/leaky-faucet",
        description: "Step-by-step guide to identifying and fixing common faucet leaks before they become expensive water waste problems.",
        keywords: ["Kitchen Plumbing", "Leak Detection"],
    },
    {
        id: 9,
        title: "Toilet Running Constantly? Here's Why",
        image: toiletRepair,
        author: "Jim Bob",
        date: "August 15, 2025",
        views: 500,
        link: "/blog/running-toilet",
        description: "Understanding why your toilet runs constantly and the simple repairs that can save you money on your water bill.",
        keywords: ["Toilet", "Save Money"],
    },
    {
        id: 10,
        title: "Water Heater Maintenance Checklist",
        image: waterHeaters,
        author: "John Doe",
        date: "August 5, 2025",
        views: 500,
        link: "/blog/water-heater-maintenance",
        description: "Essential maintenance tasks to extend your water heater's lifespan and maintain optimal performance throughout the year.",
        keywords: ["Water Heater", "Seasonal Plumbing"],
    },
    {
        id: 11,
        title: "Upgrading Your Kitchen Faucet",
        image: faucets,
        author: "Jane Smith",
        date: "July 28, 2025",
        views: 500,
        link: "/blog/kitchen-upgrade",
        description: "Transform your kitchen with a new faucet installation that combines style, functionality, and water efficiency.",
        keywords: ["Kitchen Plumbing"],
    },
    {
        id: 12,
        title: "Toilet Installation Best Practices",
        image: toiletRepair,
        author: "Jim Bob",
        date: "July 20, 2025",
        views: 500,
        link: "/blog/toilet-installation",
        description: "Professional toilet installation techniques that ensure proper sealing, stability, and long-term reliability.",
        keywords: ["Toilet", "Bathroom Plumbing"],
    },
    {
        id: 13,
        title: "Signs Your Water Heater Needs Replacement",
        image: waterHeaters,
        author: "John Doe",
        date: "July 12, 2025",
        views: 500,
        link: "/blog/water-heater-replacement",
        description: "Key warning signs that indicate it's time to replace your aging water heater before it fails completely.",
        keywords: ["Water Heater", "Heating Service"],
    },
    {
        id: 14,
        title: "Choosing the Right Bathroom Faucet",
        image: faucets,
        author: "Jane Smith",
        date: "July 5, 2025",
        views: 500,
        link: "/blog/choosing-faucet",
        description: "Expert advice on selecting bathroom faucets that match your style preferences while meeting practical needs.",
        keywords: ["Bathroom Plumbing"],
    },
    {
        id: 15,
        title: "Toilet Clog Prevention Tips",
        image: toiletRepair,
        author: "Jim Bob",
        date: "June 28, 2025",
        views: 500,
        link: "/blog/clog-prevention",
        description: "Simple habits and maintenance practices to prevent toilet clogs and avoid costly emergency plumbing calls.",
        keywords: ["Toilet", "Drain Service"],
    },
    {
        id: 16,
        title: "Water Heater Energy Efficiency Guide",
        image: waterHeaters,
        author: "John Doe",
        date: "June 20, 2025",
        views: 5020,
        link: "/blog/energy-efficiency",
        description: "Practical tips to improve your water heater's energy efficiency and reduce your monthly utility bills significantly.",
        keywords: ["Water Heater", "Save Money"],
    },
    {
        id: 17,
        title: "Faucet Water Pressure Problems",
        image: faucets,
        author: "Jane Smith",
        date: "June 12, 2025",
        views: 5000,
        link: "/blog/water-pressure",
        description: "Diagnosing and fixing low water pressure issues in your faucets to restore optimal flow throughout your home.",
        keywords: ["Kitchen Plumbing", "Plumbing System"],
    },
    {
        id: 18,
        title: "Eco-Friendly Toilet Options",
        image: toiletRepair,
        author: "Jim Bob",
        date: "June 5, 2025",
        views: 5100,
        link: "/blog/eco-toilets",
        description: "Discover water-saving toilet technologies that help conserve resources while maintaining excellent performance.",
        keywords: ["Toilet", "Water Quality", "Save Money"],
    },
];